# Generated by Django 3.2.10 on 2021-12-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
