# Generated by Django 3.2.10 on 2021-12-31 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_success'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='finished_at',
        ),
    ]
