# Generated by Django 3.2.10 on 2022-01-01 13:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20220101_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 1, 13, 43, 28, 106245, tzinfo=utc)),
        ),
    ]
